### ISSUE TITLE
networkaudiod troubles + init script patch

### ISSUE THREAD

**Issue by pms967** [fedeliallalinea/gallifrey#1]
Hi,

I had various troubles with "networkaudiod" on Gentoo (x64). 

First of all, NAD does crash as soon as hqplayer tries to connect to it:
`# networkaudiod_3.5.0-34_amd64_stretch`
`[networkaudiod_3.5.0-34_amd64_stretch] (4281): networkaudiod Copyright (C) 2011-2016 Jussi Laako / Signalyst. All rights reserved.`
`[networkaudiod_3.5.0-34_amd64_stretch] (4281): asoundlib version: 1.0.29`
`Illegal instruction`
 
On 'dmesg' I get msgs like these:
`[  229.869430] traps: networkaudiod[2432] trap invalid opcode ip:55dd101541d8 sp:7ffe521437a0 error:0`
`[  229.869441]  in networkaudiod[55dd1011b000+65000]`
`[  293.168137] traps: networkaudiod[2592] trap invalid opcode ip:555e9cbed1d8 sp:7ffc59209570 error:0`
`[  293.168147]  in networkaudiod[555e9cbb4000+65000]`

Eventually I found out that the only binary which works (at least, on my system) is the one from this "trusty" package:
https://www.signalyst.eu/bins/naa/linux/trusty/networkaudiod_3.4.0-29_amd64.deb

N.B.: of course this is just FYI and documentation... it's none of your fault.

I also had troubles with the init script failing to start the service (complaining about "missing pid file", etc). Also the log file was not written.

I have manage to get everything to work by modifying the init script this way:

```
--- networkaudiod.init.d.orig   2017-03-14 19:07:49.963980352 +0100
+++ networkaudiod.init.d        2017-03-14 19:01:22.637982814 +0100
@@ -8,9 +8,11 @@
 user="networkaudiod:networkaudiod"
 logfile="/var/log/networkaudiod.log"
 command="/usr/sbin/networkaudiod"
-command_args="-D"
+#command_args="-D"
+command_args=""
 pidfile="/run/networkaudiod.pid"
-start_stop_daemon_args="--pidfile ${pidfile} --user ${user}"
+#start_stop_daemon_args="--pidfile ${pidfile} --user ${user}"
+start_stop_daemon_args="--nicelevel -10 --background --make-pidfile --stderr ${logfile} --user ${user}"

 depend() {
     need net
@@ -20,4 +22,5 @@

 start_pre() {
     checkpath --file --owner $user --mode 0644 $logfile
+    #checkpath --file --owner $user --mode 0644 $pidfile
 }

```

My 2¢.

**Comment by fedeliallalinea** [comment]
networkaudiod has been removed from overlay
