### ISSUE TITLE
kde-plasma/gmenu-dbusmenu-proxy and qtcore-5.11.0_rc

### ISSUE THREAD

**Issue by akaelover** [fedeliallalinea/gallifrey#3]
I have a problem when updating.

Does not support QTcore 5.11

ebuild U #] dev-qt / qtcore-5.11.0_rc [5.9.5]
[ebuild N *] kde-plasma / gmenu-dbusmenu-proxy-9999 USE = "- debug"

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-qt / qtcore: 5

   (dev-qt / qtcore-5.11.0_rc: 5 / 5.11 :: gentoo, ebuild scheduled for merge) pulled in by
     > = dev-qt / qtcore-5.10.1: 5 required by (kde-plasma / gmenu-dbusmenu-proxy-9999: 0/0 :: gallifrey, ebuild scheduled for merge)
     ^^^^^^^^^^

**Comment by fedeliallalinea** [comment]
kde-plasma/gmenu-dbusmenu-proxy has been removed from overlay
