### ISSUE TITLE
APL fails to build under GCC-10

### ISSUE THREAD

**Issue by ahyangyi** [fedeliallalinea/gallifrey#5]
Apparently it tries to build with -Werror and fails. Adding `-Wno-error=class-memaccess` fixes it.

I uploaded a modified version of your ebuild here:

https://github.com/ahyangyi/ahyangyi-overlay/blob/master/dev-util/apl/apl-1.8.ebuild

**Comment by fedeliallalinea** [comment]
Sorry for delay I didn't think anyone was using my overlay (or any ebuild included in it).
I think better way is using [flag-o-matic eclass](https://devmanual.gentoo.org/eclass-reference/flag-o-matic.eclass/index.html) for add cflags.
I don't have gcc-10 installed for test.
